export const questionsData = [
  {
    id: 1,
    type: "mcq",
    text: "What is the capital of France?",
    options: ["Berlin", "Paris", "Rome"],
    correctAnswer: "Paris",
  },
  {
    id: 2,
    type: "mcq",
    text: "2 + 2 = ?",
    options: ["3", "4", "5"],
    correctAnswer: "4",
  },
  { id: 3, type: "tf", text: "The Earth is flat.", correctAnswer: "False" },
  {
    id: 4,
    type: "tf",
    text: "JavaScript is a programming language.",
    correctAnswer: "True",
  },
  {
    id: 5,
    type: "mcq",
    text: "Which tag creates a hyperlink in HTML?",
    options: ["<a>", "<p>", "<div>"],
    correctAnswer: "<a>",
  },
  {
    id: 6,
    type: "mcq",
    text: "CSS stands for?",
    options: [
      "Cascading Style Sheets",
      "Computer Style System",
      "Creative Sheet Styles",
    ],
    correctAnswer: "Cascading Style Sheets",
  },
  {
    id: 7,
    type: "mcq",
    text: "Which company created React?",
    options: ["Google", "Facebook (Meta)", "Microsoft"],
    correctAnswer: "Facebook (Meta)",
  },
  {
    id: 8,
    type: "tf",
    text: "LocalStorage persists after page refresh.",
    correctAnswer: "True",
  },
  {
    id: 9,
    type: "mcq",
    text: "HTTP status for 'Not Found'?",
    options: ["200", "301", "404"],
    correctAnswer: "404",
  },
  {
    id: 10,
    type: "mcq",
    text: "Which is NOT a JavaScript data type?",
    options: ["Number", "Boolean", "Character"],
    correctAnswer: "Character",
  },
  {
    id: 11,
    type: "tf",
    text: "In JS, `===` checks value only (not type).",
    correctAnswer: "False",
  },
  {
    id: 12,
    type: "mcq",
    text: "Which array method adds to the end?",
    options: ["push()", "shift()", "unshift()"],
    correctAnswer: "push()",
  },
  {
    id: 13,
    type: "mcq",
    text: "Git command to create a branch?",
    options: ["git fork", "git branch <name>", "git init <name>"],
    correctAnswer: "git branch <name>",
  },
  {
    id: 14,
    type: "mcq",
    text: "SQL command to read data?",
    options: ["INSERT", "SELECT", "UPDATE"],
    correctAnswer: "SELECT",
  },
  {
    id: 15,
    type: "tf",
    text: "Flexbox is used for 1-D layout in CSS.",
    correctAnswer: "True",
  },
];
