export const questionsData = [
  {
    id: 1,
    type: "tf",
    category: "General",
    text: "The Earth revolves around the Sun.",
    correctAnswer: "True",
  },
  {
    id: 2,
    type: "mcq",
    category: "General",
    text: "Which of the following are programming languages?",
    options: ["Python", "HTML", "JavaScript", "CSS"],
    correctAnswers: ["Python", "JavaScript"],
  },
  {
    id: 3,
    type: "mcq",
    category: "General",
    text: "Which gas do humans need to survive?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
    correctAnswers: ["Oxygen"],
  },
  {
    id: 4,
    type: "tf",
    category: "General",
    text: "Water boils at 90°C at sea level.",
    correctAnswer: "False",
  },
  {
    id: 5,
    type: "mcq",
    category: "General",
    text: "Which of the following are planets?",
    options: ["Mars", "Venus", "Pluto", "Sun"],
    correctAnswers: ["Mars", "Venus", "Pluto"],
  },
  {
    id: 6,
    type: "tf",
    category: "General",
    text: "The Pacific Ocean is the largest ocean on Earth.",
    correctAnswer: "True",
  },

  {
    id: 7,
    type: "mcq",
    category: "HTML",
    text: "Which of the following are semantic HTML elements?",
    options: ["<header>", "<footer>", "<div>", "<section>"],
    correctAnswers: ["<header>", "<footer>", "<section>"],
  },
  {
    id: 8,
    type: "tf",
    category: "HTML",
    text: "The <img> tag in HTML is used to display an image.",
    correctAnswer: "True",
  },
  {
    id: 9,
    type: "mcq",
    category: "HTML",
    text: "Which HTML tags are used for lists?",
    options: ["<ul>", "<ol>", "<li>", "<span>"],
    correctAnswers: ["<ul>", "<ol>", "<li>"],
  },
  {
    id: 10,
    type: "tf",
    category: "HTML",
    text: "The <title> tag defines the title of the document in the browser tab.",
    correctAnswer: "True",
  },
  {
    id: 11,
    type: "mcq",
    category: "HTML",
    text: "Which of the following attributes belong to the <img> tag?",
    options: ["src", "alt", "href", "title"],
    correctAnswers: ["src", "alt", "title"],
  },
  {
    id: 12,
    type: "tf",
    category: "HTML",
    text: "HTML stands for Hyperlinks and Text Markup Language.",
    correctAnswer: "False",
  },

  {
    id: 13,
    type: "mcq",
    category: "CSS",
    text: "Which of the following are valid CSS units?",
    options: ["px", "em", "%", "kg"],
    correctAnswers: ["px", "em", "%"],
  },
  {
    id: 14,
    type: "tf",
    category: "CSS",
    text: "Flexbox in CSS is used for 2-D layouts.",
    correctAnswer: "False",
  },
  {
    id: 15,
    type: "mcq",
    category: "CSS",
    text: "Which CSS properties are related to text styling?",
    options: ["color", "font-size", "font-weight", "border"],
    correctAnswers: ["color", "font-size", "font-weight"],
  },
  {
    id: 16,
    type: "tf",
    category: "CSS",
    text: "The 'id' selector in CSS starts with '#'.",
    correctAnswer: "True",
  },
  {
    id: 17,
    type: "mcq",
    category: "CSS",
    text: "Which of the following are positioning values in CSS?",
    options: ["absolute", "relative", "fixed", "float"],
    correctAnswers: ["absolute", "relative", "fixed"],
  },
  {
    id: 18,
    type: "tf",
    category: "CSS",
    text: "The 'z-index' property controls the stacking order of elements.",
    correctAnswer: "True",
  },

  {
    id: 19,
    type: "tf",
    category: "JavaScript",
    text: "JavaScript is the same as Java.",
    correctAnswer: "False",
  },
  {
    id: 20,
    type: "mcq",
    category: "JavaScript",
    text: "Which of the following are JavaScript frameworks/libraries?",
    options: ["React", "Vue", "Angular", "MongoDB"],
    correctAnswers: ["React", "Vue", "Angular"],
  },
  {
    id: 21,
    type: "mcq",
    category: "JavaScript",
    text: "Which array methods modify the array?",
    options: ["push()", "pop()", "map()", "filter()"],
    correctAnswers: ["push()", "pop()"],
  },
  {
    id: 22,
    type: "tf",
    category: "JavaScript",
    text: "In JavaScript, '===' checks both value and type.",
    correctAnswer: "True",
  },
  {
    id: 23,
    type: "mcq",
    category: "JavaScript",
    text: "Which of the following are JavaScript data types?",
    options: ["Number", "Boolean", "Character", "String"],
    correctAnswers: ["Number", "Boolean", "String"],
  },
  {
    id: 24,
    type: "mcq",
    category: "JavaScript",
    text: "Which of the following are looping statements in JS?",
    options: ["for", "while", "foreach", "do...while"],
    correctAnswers: ["for", "while", "do...while"],
  },
  {
    id: 25,
    type: "tf",
    category: "JavaScript",
    text: "Functions in JavaScript can be assigned to variables.",
    correctAnswer: "True",
  },
];
