export const questionsData = [
  {
    id: 1,
    type: "mcq",
    category: "General",
    text: "What is the capital of France?",
    options: ["Berlin", "Paris", "Rome"],
    correctAnswer: "Paris",
  },
  {
    id: 2,
    type: "mcq",
    category: "General",
    text: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter"],
    correctAnswer: "Mars",
  },
  {
    id: 3,
    type: "tf",
    category: "General",
    text: "The Earth is flat.",
    correctAnswer: "False",
  },
  {
    id: 4,
    type: "mcq",
    category: "General",
    text: "2 + 5 = ?",
    options: ["5", "7", "9"],
    correctAnswer: "7",
  },
  {
    id: 5,
    type: "mcq",
    category: "General",
    text: "Which ocean is the largest?",
    options: ["Atlantic", "Indian", "Pacific"],
    correctAnswer: "Pacific",
  },
  {
    id: 6,
    type: "tf",
    category: "General",
    text: "Water boils at 100°C at sea level.",
    correctAnswer: "True",
  },

  {
    id: 7,
    type: "mcq",
    category: "HTML",
    text: "Which tag creates a hyperlink in HTML?",
    options: ["<a>", "<p>", "<div>"],
    correctAnswer: "<a>",
  },
  {
    id: 8,
    type: "mcq",
    category: "HTML",
    text: "Which HTML tag is used for the largest heading?",
    options: ["<h1>", "<h6>", "<heading>"],
    correctAnswer: "<h1>",
  },
  {
    id: 9,
    type: "tf",
    category: "HTML",
    text: "The <img> tag in HTML is used to insert an image.",
    correctAnswer: "True",
  },
  {
    id: 10,
    type: "mcq",
    category: "HTML",
    text: "Which attribute specifies an image source in HTML?",
    options: ["href", "src", "alt"],
    correctAnswer: "src",
  },
  {
    id: 11,
    type: "mcq",
    category: "HTML",
    text: "Which element is used to create a numbered list?",
    options: ["<ul>", "<ol>", "<li>"],
    correctAnswer: "<ol>",
  },
  {
    id: 12,
    type: "tf",
    category: "HTML",
    text: "HTML stands for Hyper Text Markup Language.",
    correctAnswer: "True",
  },

  {
    id: 13,
    type: "mcq",
    category: "CSS",
    text: "CSS stands for?",
    options: [
      "Cascading Style Sheets",
      "Computer Style System",
      "Creative Sheet Styles",
    ],
    correctAnswer: "Cascading Style Sheets",
  },
  {
    id: 14,
    type: "tf",
    category: "CSS",
    text: "Flexbox in CSS is used for 1-D layouts.",
    correctAnswer: "True",
  },
  {
    id: 15,
    type: "mcq",
    category: "CSS",
    text: "Which CSS property changes the text color?",
    options: ["color", "text-color", "font-color"],
    correctAnswer: "color",
  },
  {
    id: 16,
    type: "mcq",
    category: "CSS",
    text: "Which CSS property controls text size?",
    options: ["font-size", "text-size", "size"],
    correctAnswer: "font-size",
  },
  {
    id: 17,
    type: "mcq",
    category: "CSS",
    text: "Which property makes text bold in CSS?",
    options: ["font-weight", "font-style", "text-bold"],
    correctAnswer: "font-weight",
  },
  {
    id: 18,
    type: "tf",
    category: "CSS",
    text: "In CSS, id selectors start with '#'.",
    correctAnswer: "True",
  },

  {
    id: 19,
    type: "tf",
    category: "JavaScript",
    text: "JavaScript is a programming language.",
    correctAnswer: "True",
  },
  {
    id: 20,
    type: "mcq",
    category: "JavaScript",
    text: "Which is NOT a JavaScript data type?",
    options: ["Number", "Boolean", "Character"],
    correctAnswer: "Character",
  },
  {
    id: 21,
    type: "mcq",
    category: "JavaScript",
    text: "Which array method adds an element to the end?",
    options: ["push()", "shift()", "unshift()"],
    correctAnswer: "push()",
  },
  {
    id: 22,
    type: "tf",
    category: "JavaScript",
    text: "In JS, `===` checks value only (not type).",
    correctAnswer: "False",
  },
  {
    id: 23,
    type: "mcq",
    category: "JavaScript",
    text: "Which keyword declares a constant in JS?",
    options: ["var", "let", "const"],
    correctAnswer: "const",
  },
  {
    id: 24,
    type: "mcq",
    category: "JavaScript",
    text: "Which symbol is used for comments in JS (single line)?",
    options: ["//", "<!--", "#"],
    correctAnswer: "//",
  },
  {
    id: 25,
    type: "tf",
    category: "JavaScript",
    text: "Functions in JS can be assigned to variables.",
    correctAnswer: "True",
  },
];
